import Head from 'next/head';
import Banner from '../components/banner';
import CardSection from '../components/Card/CardSection';
import Navbar from '../components/Navbar';

export async function getServerSideProps() {
  const response = await fetch(
    `https://youtube.googleapis.com/youtube/v3/search?part=snippet&maxResults=20&q=food&key=${process.env.YOUTUBE_API_KEY}`
  );
  const data = await response.json();
  const videos = data.items.map((item) => ({
    name: item.snippet.title,
    id: item.id.videoId,
    imgURL: item.snippet.thumbnails.high.url,
  }));
  return { props: { videos } };
}

export default function Home(props) {
  const { videos } = props;
  return (
    <div>
      <Head>
        <title>Netflix</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar email="shboulv1@gmail.com" />
      <Banner title={'The Red Dog !'} subTitle={'a very cute dog'} />
      <CardSection title="Movies" videos={videos} />
    </div>
  );
}
