// React
import { useEffect, useState } from 'react';
// next
import Head from 'next/head';
// Components
import Banner from '../components/banner';
import CardSection from '../components/Card/CardSection';
import Navbar from '../components/Navbar';
// lib
import { magic } from '../lib/magic-links';
export async function getServerSideProps() {
  const response = await fetch(
    `https://youtube.googleapis.com/youtube/v3/search?part=snippet&maxResults=20&q=travel&key=${process.env.YOUTUBE_API_KEY}`
  );
  const data = await response.json();
  const videos = data.items.map((item) => ({
    name: item?.snippet?.title,
    id: item?.id?.videoId,
    imgURL: item?.snippet?.thumbnails?.high?.url,
  }));
  return { props: { videos } };
}

export default function Home(props) {
  const [email, setEmail] = useState('');
  useEffect(() => {
    const getUserMetaData = async () => {
      try {
        const userMetadata = await magic.user.getMetadata();
        setEmail(userMetadata.email);
      } catch (error) {
        console.log(error);
      }
    };
    getUserMetaData();
  }, []);
  const { videos } = props;
  return (
    <div>
      <Head>
        <title>Netflix</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Navbar email={email} />
      <Banner title={'The Red Dog !'} subTitle={'a very cute dog'} />
      <CardSection title="Movies" videos={videos} />
    </div>
  );
}
